### Schema
DROP DATABASE IF EXISTS CHANGE ME;
CREATE DATABASE CHANGE ME;
USE CHANGE ME;

CREATE TABLE CHANGE ME
(
	id int NOT NULL AUTO_INCREMENT,
	name varchar(255) NOT NULL,
	bool BOOLEAN DEFAULT false,
	PRIMARY KEY (id)
);
